"""hq companions for blobs

Revision ID: 75a8d9168c20
Revises: a3aee41de9d6
Create Date: 2026-10-09 01:31:47.984067

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '75a8d9168c20'
down_revision: Union[str, Sequence[str], None] = 'a3aee41de9d6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blob_variants',
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('ogg_sha', sa.String(length=64), nullable=False),
    sa.Column('wav_sha', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['project_id', 'ogg_sha'], ['blobs.project_id', 'blobs.sha256'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id', 'wav_sha'], ['blobs.project_id', 'blobs.sha256'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('project_id', 'ogg_sha')
    )
    op.create_index('ix_blob_variants_wav', 'blob_variants', ['project_id', 'wav_sha'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_blob_variants_wav', table_name='blob_variants')
    op.drop_table('blob_variants')
    # ### end Alembic commands ###
