"""blobs record their media type

Revision ID: a3aee41de9d6
Revises: dd504c7b77e3
Create Date: 2026-10-09 01:14:07.619435

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a3aee41de9d6'
down_revision: Union[str, Sequence[str], None] = 'dd504c7b77e3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blobs', sa.Column('ext', sa.String(), server_default='ogg', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('blobs', 'ext')
    # ### end Alembic commands ###
